// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllDataFromDB() {
  return window['go']['backend']['Importer']['DeleteAllDataFromDB']();
}

export function ImportExcel(arg1) {
  return window['go']['backend']['Importer']['ImportExcel'](arg1);
}

export function SelectAndImportExcel() {
  return window['go']['backend']['Importer']['SelectAndImportExcel']();
}
