// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ImportExcel(arg1:string):Promise<backend.ExcelData>;

export function SelectAndImportExcel():Promise<backend.ExcelData>;
